/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package april.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class gps_tiepoint_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public double lle[];
    public double xyzt[];
 
    public gps_tiepoint_t()
    {
        lle = new double[3];
        xyzt = new double[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x9b67cebafcb530d2L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(april.lcmtypes.gps_tiepoint_t.class))
            return 0L;
 
        classes.add(april.lcmtypes.gps_tiepoint_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.lle[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeDouble(this.xyzt[a]); 
        }
 
    }
 
    public gps_tiepoint_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public gps_tiepoint_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static april.lcmtypes.gps_tiepoint_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        april.lcmtypes.gps_tiepoint_t o = new april.lcmtypes.gps_tiepoint_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.lle = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.lle[a] = ins.readDouble();
        }
 
        this.xyzt = new double[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.xyzt[a] = ins.readDouble();
        }
 
    }
 
    public april.lcmtypes.gps_tiepoint_t copy()
    {
        april.lcmtypes.gps_tiepoint_t outobj = new april.lcmtypes.gps_tiepoint_t();
        outobj.utime = this.utime;
 
        outobj.lle = new double[(int) 3];
        System.arraycopy(this.lle, 0, outobj.lle, 0, 3); 
        outobj.xyzt = new double[(int) 4];
        System.arraycopy(this.xyzt, 0, outobj.xyzt, 0, 4); 
        return outobj;
    }
 
}

