/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package april.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class kvh_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public double rads;
    public short nsamples;
    public int samples[];
 
    public kvh_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xdd5cbeab53c836b7L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(april.lcmtypes.kvh_t.class))
            return 0L;
 
        classes.add(april.lcmtypes.kvh_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeDouble(this.rads); 
 
        outs.writeShort(this.nsamples); 
 
        for (int a = 0; a < this.nsamples; a++) {
            outs.writeInt(this.samples[a]); 
        }
 
    }
 
    public kvh_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public kvh_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static april.lcmtypes.kvh_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        april.lcmtypes.kvh_t o = new april.lcmtypes.kvh_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.rads = ins.readDouble();
 
        this.nsamples = ins.readShort();
 
        this.samples = new int[(int) nsamples];
        for (int a = 0; a < this.nsamples; a++) {
            this.samples[a] = ins.readInt();
        }
 
    }
 
    public april.lcmtypes.kvh_t copy()
    {
        april.lcmtypes.kvh_t outobj = new april.lcmtypes.kvh_t();
        outobj.utime = this.utime;
 
        outobj.rads = this.rads;
 
        outobj.nsamples = this.nsamples;
 
        outobj.samples = new int[(int) nsamples];
        if (this.nsamples > 0)
            System.arraycopy(this.samples, 0, outobj.samples, 0, this.nsamples); 
        return outobj;
    }
 
}

