/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package april.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class ubx_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public byte cls;
    public byte id;
    public int len;
    public byte data[];
 
    public ubx_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xc9b5217b00475f69L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(april.lcmtypes.ubx_t.class))
            return 0L;
 
        classes.add(april.lcmtypes.ubx_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeByte(this.cls); 
 
        outs.writeByte(this.id); 
 
        outs.writeInt(this.len); 
 
        if (this.len > 0)
            outs.write(this.data, 0, len);
 
    }
 
    public ubx_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public ubx_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static april.lcmtypes.ubx_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        april.lcmtypes.ubx_t o = new april.lcmtypes.ubx_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.cls = ins.readByte();
 
        this.id = ins.readByte();
 
        this.len = ins.readInt();
 
        this.data = new byte[(int) len];
        ins.readFully(this.data, 0, len); 
    }
 
    public april.lcmtypes.ubx_t copy()
    {
        april.lcmtypes.ubx_t outobj = new april.lcmtypes.ubx_t();
        outobj.utime = this.utime;
 
        outobj.cls = this.cls;
 
        outobj.id = this.id;
 
        outobj.len = this.len;
 
        outobj.data = new byte[(int) len];
        if (this.len > 0)
            System.arraycopy(this.data, 0, outobj.data, 0, this.len); 
        return outobj;
    }
 
}

